# Excluded dependencies groupId:artifactId
excluded-dependencies:
  - io.vertx:vertx-lang-js
  - io.vertx:vertx-lang-groovy
  - io.vertx:vertx-lang-ceylon
  - io.vertx:vertx-lang-kotlin
  - io.vertx:vertx-lang-ruby
  - io.vertx:vertx-lang-scala

# Excluded resources - path relative to the project root, ${module} is the module name.
excluded-resources:
 - src/main/resources/${module}/*.rb
 - src/main/resources/${module}-js/*.js

# Plugin to remove from the build
excluded-plugins:
 - kotlin-maven-plugin
 - jsdoc3-maven-plugin
 - gem-maven-plugin

# Profile to activate when generating the pom
profiles:
  - docs
  - release

# Project version, ${version} is the project version
version: ${version}


  